// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Return Neelanjana Basu's public profile: name, current focus, location, and links to her site, GitHub, LinkedIn, and Substack.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Neelanjana Basu",
      headline: "I build AI products end to end.",
      bio: "Ten years in product before that, most of it at Amazon, most recently Senior Product Manager on Add to Cart in Search. Open to AI product roles.",
      location: "London, UK",
      email: "neelanjanabasu13@gmail.com",
      links: {
        site: "https://neelanjanabasu.lovable.app/",
        github: "https://github.com/neelanjanabasu13",
        linkedin: "https://www.linkedin.com/in/neelanjana-basu",
        substack: "https://neelanjana.substack.com/"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/list-ai-projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
var projects = [
  {
    title: "Recipe2Reel",
    platform: "ElevenLabs",
    award: "Winner, ElevenLabs ElevenCreative Challenge",
    hook: "One-click AI reels for food creators: image, video, voiceover and music chained into a single template.",
    links: [
      { label: "Build story", url: "https://neelanjana.substack.com/p/i-entered-an-ai-challenge-on-a-whim" }
    ]
  },
  {
    title: "Slack Agent for Invisible Work",
    platform: "Slack + Replit",
    hook: "A Slack agent that surfaces the work nobody sees, built for the Devpost Agent Challenge.",
    links: [
      { label: "Build story", url: "https://neelanjana.substack.com/p/i-cooked-up-a-slack-agent-that-makes" },
      { label: "GitHub", url: "https://github.com/neelanjanabasu13/receipts-app" }
    ]
  },
  {
    title: "PM Sandbox",
    platform: "Bolt.new",
    hook: "A flight simulator for product-manager interviews. Practice 3,400+ real product sense/execution/strategy questions with guided, gamified drills and AI feedback.",
    links: [
      { label: "Live", url: "https://product-sense-sandbox.bolt.host/" },
      { label: "GitHub", url: "https://github.com/neelanjanabasu13/pm-sandbox" }
    ]
  },
  {
    title: "It's Day 1",
    platform: "Lovable",
    hook: "Turn the thing you just shipped into real distribution picks, with links, specific actions, and honest guidance on where to show up first.",
    links: [
      { label: "Live", url: "https://it-is-day1.lovable.app/" },
      { label: "GitHub", url: "https://github.com/neelanjanabasu13/it-is-day1" }
    ]
  },
  {
    title: "Email Agent",
    platform: "Codex",
    hook: "My first AI agent: automating email triage and drafting end to end, the build that started the Shipping Anyway series.",
    links: [
      { label: "Build story", url: "https://neelanjana.substack.com/p/shipping-anyway-series" },
      { label: "GitHub", url: "https://github.com/neelanjanabasu13/task-digest-agent" }
    ]
  },
  {
    title: "Assembli",
    platform: "Omma",
    hook: "Interactive 3D assembly guides for furniture retailers. Flat-pack returns cost $20-30 per unit; one in five is a comprehension failure.",
    links: [
      { label: "Live", url: "https://omma.build/p/matte-black-sneaker-studio-shot-xn5evb" },
      { label: "Build story", url: "https://substack.com/home/post/p-207773480" }
    ]
  },
  {
    title: "Decision Gym",
    platform: "Figma Make",
    hook: "Polymarket for life decisions: practice judgment, get scored, build calibration.",
    links: [
      { label: "Live", url: "https://flower-plugin-92759538.figma.site/" },
      { label: "GitHub", url: "https://github.com/neelanjanabasu13/DecisionGym" }
    ]
  },
  {
    title: "VenueScout",
    platform: "Codex",
    hook: "An AI agent that sourced and contacted venues for a toddler's birthday party, end to end.",
    links: [
      { label: "Build story", url: "https://neelanjana.substack.com/p/building-an-ai-agent-to-find-my-toddlers" },
      { label: "GitHub", url: "https://github.com/neelanjanabasu13/venuescout-automation" }
    ]
  },
  {
    title: "Product Genome Studio",
    platform: "Lovable",
    hook: "A hands-on simulator for product judgment: pick customer journey patterns from companies that nailed them, see the trade-offs, and synthesize the best of all worlds.",
    links: [
      { label: "Live", url: "https://productgenomestudio.lovable.app/" },
      { label: "GitHub", url: "https://github.com/neelanjanabasu13/productgenomestudio" },
      { label: "Build story", url: "https://devpost.com/software/product-genome-studio" }
    ]
  },
  {
    title: "WhatNowKid Activity Finder",
    platform: "Lovable",
    hook: "An activity finder for parents scrambling to answer 'what now?'. It surfaces kid-friendly things to do based on the child's age, location, and mood.",
    links: [
      { label: "Live", url: "https://whatnowkid-activity-finder.lovable.app/" },
      { label: "GitHub", url: "https://github.com/neelanjanabasu13/whatnowkid-activity-finder" }
    ]
  }
];
var list_ai_projects_default = defineTool2({
  name: "list_ai_projects",
  title: "List AI projects",
  description: "List the AI products Neelanjana has built end to end during her career break, including platform, one-line hook, and links to live demos, build stories, or repos.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
    structuredContent: { projects }
  })
});

// src/lib/mcp/tools/list-amazon-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
var projects2 = [
  {
    title: "Add to Cart on Search",
    impact: "$2B revenue impact",
    tags: ["E-commerce", "Search", "UX"],
    story: "Believe it or not, you couldn't add products to your cart directly from Amazon's search results until 2023. The idea felt almost too obvious to justify a PRFAQ, so imagine our surprise when the first A/B test came back negative even as customers bought more items and built bigger baskets. After many rabbit holes, the culprit was caught: measurement models trained on three decades of a single happy path had learned that fewer product-page visits meant fewer purchases. A textbook case of Goodhart's law. Once we fixed the measurement, the experiment alone generated over half a billion dollars, and the broader charter ultimately drove more than $2B."
  },
  {
    title: "Quantity Information System",
    impact: "$250M revenue impact",
    tags: ["Data Systems", "ML", "UX"],
    story: "Customers kept receiving different quantities from what they ordered. In consumables, that is the end of a shopping habit, and habit is the whole business. The obvious fix was to make quantity bigger and bolder on the page, but the real problem ran deeper: only 1% of search results had structured quantity data, while the other 99% lived in free text written by hundreds of thousands of sellers across dozens of languages. Instead of a prettier label, I rebuilt the foundation: a new ML model, quantity published as a derived attribute on its own API so seller content was never overwritten, and new listing templates so the catalog couldn't quietly decay again. Accuracy improved from 1% to 95% across 5M products and unlocked $250M in incremental revenue."
  },
  {
    title: "Visual Navigation",
    impact: "$71M annualised uplift globally",
    tags: ["Search", "Navigation", "UX"],
    story: "Most consumables searches were broad ones like cleaning products or healthy snacks, and customers kept telling us the same thing: they didn't know where to start because everything looked the same. We had taken the visual ease of walking a supermarket aisle and replaced it with a wall of text. My first attempt at fixing it failed within days, but the instrumentation I had insisted on made the problem obvious: we had chosen the right attribute, but many of its values led to dead ends. Two weeks later we relaunched with image carousels built around what customers actually clicked across multiple attributes, and it delivered a $71M annualised uplift globally."
  },
  {
    title: "Range Review Automation (Amazon Pantry)",
    impact: "\xA325M revenue",
    tags: ["Automation", "Analytics"],
    story: "Pantry was meant to be Amazon's corner shop for everyday essentials, but the assortment reflected what suppliers listed rather than what customers actually bought. We had a national feed of live Nielsen point-of-sale data sitting almost unused, so I turned it into a merchandising tool organised the way a real supermarket allocates shelf space. \xA325M of extra cash earned just by choosing better selection for our customers."
  }
];
var list_amazon_projects_default = defineTool3({
  name: "list_amazon_projects",
  title: "List Amazon projects",
  description: "List the four products Neelanjana shipped and scaled at Amazon, including the impact, tags, and the full behind-the-scenes story for each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(projects2, null, 2) }],
    structuredContent: { projects: projects2 }
  })
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
var experience = [
  {
    company: "Amazon",
    location: "London, UK",
    roles: [
      {
        title: "Senior Product Manager, Consumables",
        period: "Jul 2020 \u2013 Sep 2025",
        summary: "Owned end-to-end product strategy for Amazon's worldwide consumables business (200M+ customers, 20 countries). Shipped Add to Cart on Search ($2B), the Quantity Information System ($250M), and Visual Navigation on search ($71M annualised)."
      },
      {
        title: "Product Manager, Amazon Pantry",
        period: "2016 \u2013 2020",
        summary: "Built the merchandising and range-review tooling for Amazon's essentials store across the UK and Europe, unlocking \xA325M of incremental revenue."
      }
    ]
  },
  {
    company: "Meru Cabs",
    location: "Mumbai, India",
    roles: [
      {
        title: "Product Manager",
        period: "Before Amazon",
        summary: "Early product work on one of India's first radio-taxi platforms, learning how to ship into ambiguous consumer markets."
      }
    ]
  }
];
var list_experience_default = defineTool4({
  name: "list_experience",
  title: "List work experience",
  description: "List Neelanjana's professional experience by company and role, with dates and a short summary of what she shipped.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
    structuredContent: { experience }
  })
});

// src/lib/mcp/tools/list-education.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
var education = [
  {
    institution: "Goa Institute of Management",
    url: "https://gim.ac.in/",
    qualification: "PGDM (MBA)"
  },
  {
    institution: "Gujarat University",
    url: "https://www.gujaratuniversity.ac.in/",
    qualification: "Undergraduate degree"
  }
];
var list_education_default = defineTool5({
  name: "list_education",
  title: "List education",
  description: "List the schools Neelanjana attended, with the qualification earned at each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(education, null, 2) }],
    structuredContent: { education }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "neelanjana-portfolio-mcp",
  title: "Neelanjana Basu Portfolio",
  version: "0.1.0",
  instructions: "Read-only tools for Neelanjana Basu's portfolio site. Use get_profile for identity and links, list_ai_projects for the AI products she has built during her career break, list_amazon_projects for the four products she shipped and scaled at Amazon, list_experience for her work history, and list_education for her schools.",
  tools: [get_profile_default, list_ai_projects_default, list_amazon_projects_default, list_experience_default, list_education_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
